language: c

sudo: false

addons:
  apt:
    packages:
      - python-virtualenv
      - gfortran
      - libgsl0-dev

install:
  - ./setup.sh
  - ./build.sh

before_install:
  - eval "$(curl https://data.kitware.com/api/v1/file/55735da88d777f649a9ba181/download | /bin/bash)"
  - eval "$(travis-install 556bd0c08d777f649a9ba139)"

script:
  - ./test.sh
  - ./package.sh
  - ./pyenv/bin/python deploy.py

env:
  global:
    - prefix=local
    - name=aRbor-packages
    - version=1.0.0
    - package_depends='["556bd0c08d777f649a9ba139"]'
    - GIRDER_URL=https://data.kitware.com/api/v1
    - GIRDER_USER=travis-packages
    - GIRDER_FOLDER=55535d828d777f082b592f55
    - secure: "nV+2gEcD8gUGrYeKNUxF9y99aoLxUrrTR+JktVaDctksuzI/hr9kL5oPN6Qhs+/fs4apQ2EWY0wOkTW1n08MrSIw/sNJxMGPuKPRuTJQY7apI/zCkplMvhc04KH8b/grp59Mlo7plr4CUCgWyTlZgcfUTYb8UllgTx/Yoy7/T7+wDcuGl1vUcdzMG0XUGhuR0eMozQkInqzbZUoDGjm9drr1anBHQ3BeUxRPT/AGP4OQSoUPoWk/gYbdaL31At8Medf7xsoBLPOGbZAhyTxbSOuLhw1X8gMWaHztYSuuEuyy8E/IiHKFhwP7wVwL8MWszXfST3msXM75ujneV/tXiTBfuRzl0lyAtdFddfTXTDFCE4/o0Jt87LsSnQ1AO+dKMH7HP4E3PHQcnjFEeE6FQWJHdgq0r2eJ+DHEPGkF1rS7I8aK22N3Znw3ouT1Haaoaj8h1iyHpRMBt0vxGxrR9PTrZmM2AWSzLLmOCjHvdHXMtRQI+ZGrEgNWbRiSuTlzpcAQMSqyBkhyi+DSDB9TmSks3G9K/fPKS2O/tTD0Lt2pLSeGDCWtow9CUl4zEvtj933iHE8rp2R/k/gSy6tw1jLZLRPZ71Vb0l8AHA2zs27/UvVXo7FnAHtfmfMAfF8n659ZuMjxM3q2tyfiat6VcR5iqy55yWNexIGPl/4JyjA="
